FROM node:18

# Create app directory
WORKDIR /app

# Copy lock files first for better caching
COPY package*.json ./

# Install dependencies and global expo-cli
RUN npm ci --silent
RUN npm install -g expo-cli

# Copy app source
COPY . .

# Expose Expo ports
EXPOSE 19000 19001 19002 8081

# Start Expo
CMD ["expo", "start", "--tunnel", "--non-interactive"]
